name: Whitelist-Manager
version: 1.0.0
main: com.murqin.whitelistmanager.WhitelistManager
api-version: '26.1'
author: Murqin
description: Console-delegated whitelist management plugin.
commands:
  wl:
    description: Oyun ici whitelist ekleme/cikarma komutu.
    usage: /wl <add|remove> <oyuncu>
  wladmin:
    description: Konsoldan whitelist yetkililerini yonetme komutu.
    usage: /wladmin <add|remove|list|reload>
